---
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Flag:
    Type: String
    Default: "True"

Conditions:
  IsTrue: !Equals [ !Ref Flag, "True" ]

Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-8b542366"
      InstanceType: t2.small
      KeyName: key
      SubnetId: "subnet-xxxxxxx"
      SecurityGroupIds:
        - "sg-xxxxxxxx"
      UserData:
        Fn::Base64:
          Fn::Sub:
            - |
              echo "Message: ${Message}"
              echo "Message: ${Message}"
              echo "Message: ${Message}"
            - Message: !If [IsTrue, "True!!!!", "False....."]
